#!/bin/bash

fail=0

./tests || fail=$((fail+1))
echo

runtest() {
    /bin/echo -En "$2 ... "
    echo "main() {$2}" | ./8cc - tmp$$.o
    gcc -o tmp$$ tmp$$.o
    local result="`./tmp$$`"
    if [ "$result" = "$1" ]; then
	echo $1
    else
	echo "NG ($result)"
	fail=$((fail+1))
    fi
}

#
# Basic tests
#
runtest 'Hello, world!' 'printf("Hello, world!");'
runtest '12.34 56.78 42' 'printf("%2.2f %2.2f %d", 12.34, 56.78, 42);'
runtest '3' 'int i=3; printf("%d", i);'
runtest '6' 'int i=3; int j=0; j=i+3; printf("%d", j);'
runtest '50' 'int i=atoi("50"); int j = i; printf("%d", j);'
runtest '15' 'int i=3; int j=i+5+7; printf("%d", j);'
runtest '-5' 'int i=3; int j=5-i-7; printf("%d", j);'

#
# Operator precedences
#
runtest '10' 'int i=3; int j=1+i*3; printf("%d", j);'
runtest '5' 'int i=9; int j=1+i/3+9/i; printf("%d", j);'

#
# Assignment
#
runtest '3' 'int i=3; int j=i; printf("%d", j);'

#
# "if" expression
#
runtest 'true' 'int i=1; if (i) { printf("true"); } else { printf("false"); }'
runtest 'false' 'int i=0; if (i) { printf("true"); } else { printf("false"); }'

#
# "while" expression
#
runtest '54321a' 'int i=5; while (i) { printf("%d", i); i=i-1; } printf("a");'

#
# "==" operator
#
runtest '1' 'int i=5; int j=5; int k=i==j; printf("%d", k);'
runtest '0' 'int i=3; int j=5; int k=i==j; printf("%d", k);'
runtest 'true'  'int i=5; int j=5; if (i==j) { printf("true"); } else { printf("false"); }'
runtest 'false' 'int i=3; int j=5; if (i==j) { printf("true"); } else { printf("false"); }'

rm -f tmp$$ tmp$$.o
echo
if [ $fail -gt 0 ]; then
    echo "Test failure(s): $fail";
else
    echo OK
fi

